### ISSUE TITLE
Possible static linkage chosen when building shared lib using rb-sys

### ISSUE THREAD

**Issue by makrisoft** [oxidize-rb/rb-sys#62]
```
librb_sys-fe5430e22a32af2b.rlib(thread.o): relocation R_X86_64_TPOFF32 against `ruby_native_thread' can not be used when making a shared object; recompile with -fPIC
```

my Cargo.toml looks kinda like:

```
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus", features = ["rb-sys-interop"] }

[dev-dependencies]
magnus = { git = "https://github.com/matsadler/magnus", features = ["embed"] }

```

**Comment by ianks** [comment]
So the solution to this is to ensure you set `resolver = "2"` in your `Cargo.toml`. Otherwise, Cargo will [unify the `magnus` features](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2), causing `embed` to be enabled, and thus Ruby to be linked. With a gem, you do not want to link libruby.

Hope this helps someone!
