### ISSUE TITLE
Add support for `x86_64-pc-windows-msvc`

### ISSUE THREAD

**Issue by ianks** [oxidize-rb/rb-sys#71]
### Goal

This will allow Rubygems to run tests against `ruby-head` on every commit for Windows.

### Solution

It may be as easy as adding `x86_64-pc-windows-msvc` to the CI matrix. Or may require more work.

https://github.com/rubygems/rubygems/pull/5747

**Comment by MSP-Greg** [comment]
I've got a branch in my fork that's passing with `ruby-head`, see [head, windows-2022, stable-x86_64-pc-windows-gnu)](https://github.com/MSP-Greg/rb-sys/runs/7442560076?check_suite_focus=true#logs)

There are four Ruby master/head builds available on Actions.  The `ucrt` & `head` builds are build using MSYS2 UCRT64 (gcc), the `mingw` build uses MSYS2 MINGW64 (gcc).

Currently, Ruby 2.4 thru 3.0 were/are built with MSYS2 MINGW64 (gcc).  Ruby 3.1 is built with MSYS2 UCRT64 (gcc).

I think all the above builds should use `stable-x86_64-pc-windows-gnu`?

MSYS2 MINGW64 (gcc) compiles with msvcrt.  MSYS2 UCRT64 (gcc) compiles with vcruntime.

The fourth build, `mswin`, is built with MSVC.  I think it should use `x86_64-pc-windows-msvc`?

While working recently with some numeric extension gems, I think the functions exported from Ruby vary between the MSYS2 MING64/UCRT64 builds and the MSVC build.  Or, if one compiles an extension gem with UCRT64, it may not work with an `mswin` Ruby, since the functions vary...

Finally, when running the CI in the RubyGems PR above, `stable-x86_64-pc-windows-gnu` installed `component 'rust-mingw'`, but the same was not install for `stable-x86_64-pc-windows-msvc` (which also installed `component 'clippy'` & `component 'rustfmt'`.  Not sure what those do.

HTH, Greg

**Comment by ianks** [comment]
@MSP-Greg Can you open a PR for this branch?

**Comment by MSP-Greg** [comment]
See PR #72.  As mentioned, not sure if there is a missing dependency when using mswin...

**Comment by ianks** [comment]
Released in v0.9.31 🎊
